<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $properties = [
            [
                'title' => 'Villa Sostenible con Certificación A en La Eliana',
                'slug' => 'villa-sostenible-certificacion-a-la-eliana',
                'description' => "Espectacular villa de nueva construcción con los más altos estándares de eficiencia energética. Esta propiedad cuenta con certificación energética A, lo que garantiza un consumo mínimo y el máximo confort.\n\nLa vivienda dispone de sistema de aerotermia para climatización y agua caliente, placas solares fotovoltaicas con capacidad de autoconsumo del 70%, ventanas de triple acristalamiento con rotura de puente térmico, y sistema SATE de aislamiento exterior.\n\nEl jardín incluye sistema de riego automatizado con recuperación de aguas pluviales. Materiales de construcción certificados y pinturas ecológicas en todo el interior.",
                'price' => 485000,
                'location' => 'La Eliana, Valencia',
                'address' => 'Urbanización El Bosque, 15',
                'surface' => 250,
                'rooms' => 4,
                'bathrooms' => 3,
                'year_built' => 2023,
                'property_type' => 'chalet',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 450,
                'co2_savings' => 2800,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'sate', 'aerothermy', 'solar_panels', 'rainwater_recovery', 'certified_wood', 'eco_paints'],
                'certifications' => ['Passivhaus', 'BREEAM'],
                'images' => ['/images/properties/villa-sostenible-1.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Piso Eco-Eficiente en Ruzafa',
                'slug' => 'piso-eco-eficiente-ruzafa',
                'description' => "Moderno piso reformado íntegramente con criterios de sostenibilidad en el corazón del barrio de Ruzafa. Certificación energética B conseguida tras una rehabilitación completa.\n\nLa vivienda cuenta con suelo radiante conectado a bomba de calor aerotérmica, ventanas de doble acristalamiento Climalit con control solar, y electrodomésticos de máxima eficiencia energética.\n\nUbicación perfecta para disfrutar de la vida del barrio más trendy de Valencia, con todos los servicios a pie de calle.",
                'price' => 265000,
                'location' => 'Ruzafa, Valencia',
                'address' => 'Calle Cuba, 34',
                'surface' => 95,
                'rooms' => 3,
                'bathrooms' => 2,
                'year_built' => 2022,
                'property_type' => 'piso',
                'status' => 'disponible',
                'energy_rating' => 'B',
                'co2_emissions' => 680,
                'co2_savings' => 1500,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'aerothermy', 'eco_paints'],
                'certifications' => ['LEED'],
                'images' => ['/images/properties/casa-ecologica-2.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Ático con Placas Solares en Benimaclet',
                'slug' => 'atico-placas-solares-benimaclet',
                'description' => "Luminoso ático con terraza de 40m² equipada con instalación fotovoltaica propia. Certificación energética A gracias a la combinación de energía solar y excelente aislamiento.\n\nVistas despejadas y orientación sur que maximiza el aprovechamiento de la luz natural. Sistema de domótica para control inteligente de consumos.\n\nEl edificio ha sido rehabilitado con sistema SATE y cuenta con zonas comunes eficientes.",
                'price' => 320000,
                'location' => 'Benimaclet, Valencia',
                'address' => 'Avenida Primado Reig, 78',
                'surface' => 110,
                'rooms' => 2,
                'bathrooms' => 2,
                'year_built' => 2021,
                'property_type' => 'atico',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 380,
                'co2_savings' => 2200,
                'energy_type' => 'solar',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'sate', 'solar_panels'],
                'certifications' => ['BREEAM'],
                'images' => ['/images/properties/piso-eficiente-3.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Casa Adosada Bioclimática en Godella',
                'slug' => 'casa-adosada-bioclimatica-godella',
                'description' => "Casa adosada diseñada siguiendo principios de arquitectura bioclimática. Orientación optimizada para captación solar pasiva en invierno y protección en verano.\n\nCuenta con sistema de ventilación con recuperador de calor, geotermia para climatización, y cubierta vegetal que mejora el aislamiento y reduce el efecto isla de calor.\n\nJardín con plantas autóctonas de bajo consumo hídrico.",
                'price' => 395000,
                'location' => 'Godella, Valencia',
                'address' => 'Camino del Huerto, 12',
                'surface' => 180,
                'rooms' => 4,
                'bathrooms' => 2,
                'year_built' => 2020,
                'property_type' => 'adosado',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 320,
                'co2_savings' => 2600,
                'energy_type' => 'geotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'sate', 'rainwater_recovery', 'certified_wood', 'eco_paints'],
                'certifications' => ['Passivhaus'],
                'images' => ['/images/properties/chalet-bioclimatico-4.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Estudio Reformado con Eficiencia B en El Carmen',
                'slug' => 'estudio-reformado-eficiencia-b-carmen',
                'description' => "Acogedor estudio completamente reformado en edificio histórico del centro de Valencia. A pesar de las limitaciones del edificio protegido, se ha conseguido certificación B.\n\nReforma realizada con materiales ecológicos, ventanas de alta eficiencia compatibles con la estética del edificio, y sistema de climatización por splits de bajo consumo.\n\nIdeal para inversión o primera vivienda.",
                'price' => 145000,
                'location' => 'El Carmen, Valencia',
                'address' => 'Calle Alta, 8',
                'surface' => 45,
                'rooms' => 1,
                'bathrooms' => 1,
                'year_built' => 2019,
                'property_type' => 'estudio',
                'status' => 'disponible',
                'energy_rating' => 'B',
                'co2_emissions' => 520,
                'co2_savings' => 800,
                'energy_type' => 'electrica',
                'sustainability_features' => ['double_glazing', 'eco_paints'],
                'certifications' => [],
                'images' => ['/images/properties/apartamento-verde-5.jpg'],
                'is_featured' => false,
            ],
            [
                'title' => 'Dúplex con Aerotermia en Paterna',
                'slug' => 'duplex-aerotermia-paterna',
                'description' => "Amplio dúplex de reciente construcción en zona residencial tranquila. Sistema de aerotermia centralizado para calefacción, refrigeración y agua caliente sanitaria.\n\nLa vivienda cuenta con dos plantas conectadas por escalera interior, terraza en planta superior y plaza de garaje con preinstalación para punto de recarga de vehículo eléctrico.\n\nComunidad con zonas verdes y piscina.",
                'price' => 285000,
                'location' => 'Paterna, Valencia',
                'address' => 'Calle del Parque, 45',
                'surface' => 140,
                'rooms' => 3,
                'bathrooms' => 2,
                'year_built' => 2022,
                'property_type' => 'duplex',
                'status' => 'reservada',
                'energy_rating' => 'B',
                'co2_emissions' => 620,
                'co2_savings' => 1400,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'aerothermy'],
                'certifications' => ['VERDE'],
                'images' => ['/images/properties/casa-pasiva-6.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Villa Sostenible en La Cañada',
                'slug' => 'villa-sostenible-la-canada',
                'description' => "Espectacular villa de diseño bioclimático con certificación Passivhaus. Cuenta con sistema de aerotermia, placas solares de 5kW y sistema de recuperación de aguas pluviales. El aislamiento térmico es de última generación (SATE 15cm), garantizando un consumo casi nulo todo el año. Jardín xerófito de bajo consumo hídrico.",
                'price' => 450000,
                'location' => 'La Cañada, Valencia',
                'address' => 'Calle Principal, 10',
                'surface' => 180,
                'rooms' => 4,
                'bathrooms' => 3,
                'year_built' => 2024,
                'property_type' => 'chalet',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 500,
                'co2_savings' => 2500,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'sate', 'aerothermy', 'solar_panels', 'rainwater_recovery'],
                'certifications' => ['Passivhaus'],
                'images' => ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80'],
                'is_featured' => true,
            ],
            [
                'title' => 'Ático con Terraza Verde en Benimaclet',
                'slug' => 'atico-terraza-verde-benimaclet',
                'description' => "Ático reformado íntegramente con materiales ecológicos y naturales (corcho, madera certificada). Dispone de una gran terraza con huerto urbano y riego automático. Ventanas de triple acristalamiento y suelo radiante por aerotermia. Ubicado en barrio consolidado con todos los servicios.",
                'price' => 285000,
                'location' => 'Benimaclet, Valencia',
                'address' => 'Calle Murta, 5',
                'surface' => 110,
                'rooms' => 3,
                'bathrooms' => 2,
                'year_built' => 2010,
                'property_type' => 'atico',
                'status' => 'disponible',
                'energy_rating' => 'B',
                'co2_emissions' => 1200,
                'co2_savings' => 1800,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'eco_paints', 'certified_wood'],
                'certifications' => [],
                'images' => ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80'],
                'is_featured' => true,
            ],
            [
                'title' => 'Adosado Eficiente en Rocafort',
                'slug' => 'adosado-eficiente-rocafort',
                'description' => "Vivienda unifamiliar con etiqueta energética A. Instalación fotovoltaica con baterías de litio para autonomía nocturna. Punto de carga para vehículo eléctrico en garaje privado. Carpintería de aluminio con rotura de puente térmico y vidrios bajo emisivos.",
                'price' => 340000,
                'location' => 'Rocafort, Valencia',
                'address' => 'Avenida Ausiàs March, 22',
                'surface' => 150,
                'rooms' => 4,
                'bathrooms' => 3,
                'year_built' => 2018,
                'property_type' => 'adosado',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 800,
                'co2_savings' => 2200,
                'energy_type' => 'solar',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'solar_panels'],
                'certifications' => ['LEED'],
                'images' => ['https://images.unsplash.com/photo-1600596542815-60c37c6525fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80'],
                'is_featured' => false,
            ],
            [
                'title' => 'Loft Industrial Rehabilitado',
                'slug' => 'loft-industrial-rehabilitado',
                'description' => "Antiguo taller convertido en vivienda loft de estilo industrial. Rehabilitación enfocada en la eficiencia energética manteniendo el carácter original. Techos altos, ventilación cruzada natural y gran aislamiento en cubierta. Ideal para teletrabajo.",
                'price' => 210000,
                'location' => 'Ruzafa, Valencia',
                'address' => 'Calle Centelles, 18',
                'surface' => 85,
                'rooms' => 1,
                'bathrooms' => 1,
                'year_built' => 1950,
                'property_type' => 'estudio',
                'status' => 'disponible',
                'energy_rating' => 'C',
                'co2_emissions' => 1800,
                'co2_savings' => 1000,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing'],
                'certifications' => [],
                'images' => ['https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80'],
                'is_featured' => false,
            ],
            [
                'title' => 'Casa de Campo Autosuficiente',
                'slug' => 'casa-campo-autosuficiente',
                'description' => "Finca rústica totalmente desconectada de la red (off-grid). Pozo propio legalizado, gran instalación solar y generador de apoyo. Construcción tradicional con muros anchos que garantizan gran inercia térmica. Olivos y almendros en producción ecológica.",
                'price' => 195000,
                'location' => 'Cheste, Valencia',
                'address' => 'Polígono 5, Parcela 12',
                'surface' => 120,
                'rooms' => 3,
                'bathrooms' => 1,
                'year_built' => 1985,
                'property_type' => 'casa',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 200,
                'co2_savings' => 3000,
                'energy_type' => 'solar',
                'sustainability_features' => ['solar_panels', 'rainwater_recovery', 'thermal_insulation'],
                'certifications' => [],
                'images' => ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&auto=format&fit=crop&w=1365&q=80'],
                'is_featured' => false,
            ],
            [
                'title' => 'Piso Familiar en Avenida Francia',
                'slug' => 'piso-familiar-avenida-francia',
                'description' => "Amplio piso con vistas a la Ciudad de las Artes. Edificio moderno con buena calificación energética. Calefacción central por gas natural y aire acondicionado por conductos. Perfecto estado de conservación. Plaza de garaje incluida.",
                'price' => 390000,
                'location' => 'Penya-Roja, Valencia',
                'address' => 'Avenida de Francia, 120',
                'surface' => 135,
                'rooms' => 4,
                'bathrooms' => 2,
                'year_built' => 2005,
                'property_type' => 'piso',
                'status' => 'disponible',
                'energy_rating' => 'D',
                'co2_emissions' => 2500,
                'co2_savings' => 500,
                'energy_type' => 'gas',
                'sustainability_features' => ['double_glazing'],
                'certifications' => [],
                'images' => ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80'],
                'is_featured' => false,
            ]
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
